### ISSUE TITLE
SNP genomic loader is loading contigs as chromosomes

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/intermine-cowpeamine#1]
11 contigs were loaded as chromosomes by the new SNPVCFFileLoader yesterday because markers are located on them. I didn't realize we had 1_* and 2_* markers on contigs, so I'll fix that, and I have a dump of the DB before that. Suspicious that it's 11 contigs.

**Comment by adf-ncgr** [comment]
11 contigs with markers of the form [12]_* is what I get too; I think it's a coincidence that it happens to match the LG count (if that's what you thought was suspicious)

**Comment by sammyjava** [comment]
Updated loader to load supercontigs when appropriate.
