### ISSUE TITLE
"Organisms" like CB27 have "-" as their <a> text in search results

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#12]
try a keyword search for CB27 and see if you can find what to click to get to the report page.

this is probably trivial and maybe this is going to be changing anyway if we go with a separate
table for Germplasm (or whatever we call it). Either way, it would also be nice if you could get to the mapping populations that the entity parented (currently seems to be only connected by naming convention).

**Comment by sammyjava** [comment]
This is resolved in current versions, although looking at this bug revealed that I have dupe strains in the current staging CowpeaMine. I think I fixed that before and just need to rebuild it....
