### ISSUE TITLE
marker report pages provide links to LIS, but no one is home at the other end

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#16]
one could consider this a LIS bug, but since we haven't had anyone doing curation of
maps for cowpea into the tripal-system, it doesn't work for cowpea the way it works for common bean. One could conceivably link to the cmap display, e.g.:
https://legumeinfo.org/traits_maps/cmap/?ref_map_set_acc=VuMucheroUCRiverside2009;ref_map_accs=VuMucheroUCRiverside2009_8;highlight=VuMucheroUCRiverside2009_8_1_0187
though I am not sure all the markers from the newer consensus map would be present there. It's probably best to just turn off this linking for now, and maybe we will have something to link to later (or when/if the linkout service supports non-genic types it could be subsumed under that mechanism)

**Comment by sammyjava** [comment]
Link duly commented out in web.properties.
