### ISSUE TITLE
SNP features try (but fail) to have an embedded JBrowse

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#4]
Probably because of their not being from the organism of the reference genome as we had discussed a few days ago?

https://datil:8443/cowpeamine/portal.do?class=GeneticMarker&externalids=1_0504

**Comment by sammyjava** [comment]
I'll work on this one after I promote the mine to production. I think it could be somewhat involved, since I don't normally touch the JBrowse stuff, it just works. I'd like to shiny up the JBrowse for genes as well, I've got an email from Vivek somewhere in the Deep Archive.

**Comment by sammyjava** [comment]
This fixed itself with the chromosome sequences in the mine.
