### ISSUE TITLE
Other mines should be friendly to cowpeamine

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#5]
I know you know about this, just getting it formally on the todo list.

**Comment by adf-ncgr** [comment]
tangentially related to this, is there a good reason not to import homologues that don't happen to have their own mine (e.g. mungbean or adzuki)? seems like just having the complete list of related genes ought to be non-problematic, and when legumemine gets the full set of genomes (including those without a species-specific mine) it could in some cases help with friendliness.

**Comment by adf-ncgr** [comment]
and even though it has a mine Cicer arietinum ICC4958 (desi) doesn't seem to appear in the lists (possibly because like cowpea it is not in the trees like CDCFrontier kabuli is)

**Comment by sammyjava** [comment]
Hrm, I agree, I should add more organisms to the homology loader. Homology is homology, the friendly mine thing is an add-on.

**Comment by sammyjava** [comment]
So these are the organisms with gene family entries in chado, I'll add them to that loader:
```
lis-chado=# select genus,species from organism where organism_id in (select distinct organism_id from featureprop,feature where featureprop.type_id=51206 and featureprop.feature_id=feature.feature_id);
   genus   |         species          
-----------+--------------------------
 Arachis   | ipaensis_K30076
 Cicer     | arietinum_ICC4958
 Medicago  | truncatula_Mt4.0
 Vigna     | radiata_VC1973A
 Trifolium | pratense_MilvusB
 Phaseolus | vulgaris_G19833
 Vigna     | angularis_Gyeongwon
 Vigna     | unguiculata_IT97K-499-35
 Cicer     | arietinum_CDCFrontier
 Glycine   | max_Williams82
 Arachis   | duranensis_V14167
 Cajanus   | cajan_ICPL87119
 Lupinus   | angustifolius_Tanjil
 Lotus     | japonicus_MG20
```

**Comment by adf-ncgr** [comment]
sounds good. just so we're on the same page, you should be able to populate everything in this list using the "gene family assignments" table. some of the species are also in the trees, but everything should be present in the featureprop table (from which the GCV helper table is derived)

**Comment by adf-ncgr** [comment]
actually, I just realized it is a bit more complicated than my last comment might lead you to believe.
what I said is true for all the legumes. but for non-legumes we don't store gene features, just the
polypeptide features that are actually in the trees. and those don't know about their family assignments other than through the trees, IIRC. Maybe we can ignore this for now, but not having arabidopsis in the homologue list might be a bummer. Or maybe you already do the right thing and take all possible ways of getting a gene family assignment into account and then ensure we don't get duplicate assignment for species that are present in both the trees and the featureprop. well, anyway, you probably get the point- it's a little heterogeneous...

**Comment by sammyjava** [comment]
Hrm, if I narrow my query above to only include **genes** that have featureprop->gene family relations, rather than perhaps proteins, I still get those 14 organisms, so those seem like they'll produce homologous genes in the (new) chado-genefamilies loader:
```
lis-chado=# select genus,species from organism where organism_id in (select distinct organism_id from featureprop,feature where feature.type_id=43076 and featureprop.type_id=51206 and featureprop.feature_id=feature.feature_id);
   genus   |         species          
-----------+--------------------------
 Arachis   | ipaensis_K30076
 Cicer     | arietinum_ICC4958
 Medicago  | truncatula_Mt4.0
 Vigna     | radiata_VC1973A
 Trifolium | pratense_MilvusB
 Phaseolus | vulgaris_G19833
 Vigna     | angularis_Gyeongwon
 Vigna     | unguiculata_IT97K-499-35
 Cicer     | arietinum_CDCFrontier
 Glycine   | max_Williams82
 Arachis   | duranensis_V14167
 Cajanus   | cajan_ICPL87119
 Lupinus   | angustifolius_Tanjil
 Lotus     | japonicus_MG20
(14 rows)
```

**Comment by adf-ncgr** [comment]
yes, what I meant to say is that if you query featureprop for gene family assignments you will get all the legume genes, but you will get none of the non-legume proteins that are assigned to gene families via the trees (hence no friendliness to thalemine). I suppose we could add featureprops for them if that makes life simpler, though I would not anticipate adding gene features for them anytime soon.

**Comment by sammyjava** [comment]
Oh, right, I was thinking Arabidopsis was in that list. Just legumes, I see. I could run the former phylotree-based loader just against Arabidopsis to pull that in. Or any other non-legume we want.
