### ISSUE TITLE
region search broken?

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#7]
clicking the link to provide an example doesn't give you one. So I tried:
Vu01:1-495933

and was told:
There has been an internal error while processing your request. The problem has been logged and will be investigated. You may also send us an email describing how you encountered this error.
The problem may be temporary in which case you might wish to go back and try your request again or you might want to go to the home page.

**Comment by sammyjava** [comment]
Fixed, some strand-specific stuff didn't get loaded, hadn't updated cowpeamine's github structure.
