### ISSUE TITLE
dropdown list of choices for types under "Enter a list of identifiers" should be extended

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#8]
doesn't seem to provide "genomic" choice like Gene

**Comment by sammyjava** [comment]
For the record (because I forgot), this requires updating webapp/resources/webapp/default-template-queries.xml and ant build-db-userprofile, blowing away the existing user profiles (yeah, pretty dumb). It does NOT require rebuilding the webapp.
