### ISSUE TITLE
should have "external links" to legumeinfo gene pages

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-cowpeamine#9]
which won't work until we do the release, but if we can't federate with ourselves it's bad...

**Comment by adf-ncgr** [comment]
PS. it would be nifty if instead of just linking to the gene pages, you could instead call the gene linkout web service and populate a set of links based on the returned results. This may not be something to try to get in place for today's release, but would be nifty in general for our mines to use the same mechanism that we do in the GCV and phylotrees for giving a range of linking options to the user.

**Comment by sammyjava** [comment]
Give me the code for the gene linkout web service, I'll punch it in at some point, maybe this aft. I can rebuild the webapp easily after it's in production, takes a minute.

**Comment by adf-ncgr** [comment]
OK, give me a minute to dredge the details at the level that I think would be useful to you.

**Comment by adf-ncgr** [comment]
OK, I think this will tell you what you need to know; note that you will need the "gensp." prefix in
order for this to work in the current implementation;
GET https://legumeinfo.org/gene_links/glyma.Glyma.01G047700/json
`[
{
href: "//legumeinfo.org/feature/Glycine/max/gene/Glyma.01G047700.Wm82.a2.v1",
text: "View LIS gene page for : Glyma.01G047700"
},
{
href: "//legumeinfo.org/lis_context_viewer/index.html#/search/lis/glyma.Glyma.01G047700/",
text: "Find similar genomic contexts at LIS for : Glyma.01G047700"
},
{
href: "http://intermine.legumefederation.org/legumemine/portal.do?class=Gene&externalids=Glyma.01G047700",
text: "View LegumeMine page for : Glyma.01G047700"
},
{
href: "http://www.soybase.org/sbt/search/search_results.php?category=FeatureName&search_term=Glyma.01G047700",
text: "view at SoyBase: Glyma.01G047700"
},
{
href: "http://phytozome.jgi.doe.gov/pz/portal.html#!results?search=0&crown=1&star=0&method=4433&searchText=Glyma.01G047700",
text: "view at Phytozome: Glyma.01G047700"
},
{
href: "http://soykb.org/gene_card.php?gene=Glyma.01G047700",
text: "view at SoyKB: Glyma.01G047700"
}
]`

**Comment by sammyjava** [comment]
Thanks, easy enough. That'll go on the post-promotion to-do list, I won't bother with the simple "view this gene on LIS" since this is mo' bettah.

**Comment by sammyjava** [comment]
Are these URLs consistently formatted? (As they must be.) This returns a 404:
https://legumeinfo.org/gene_links/vigun.Vigun05g296900
Not sure what else to use that's the same for all orgs, that's the equivalent of your Glyma example I think. Or just broken?

Needless to say, this, which works for the gene page, also does not work for the JSON:
https://legumeinfo.org/gene_links/vigun.IT97K-499-35.gnm1.ann1.Vigun01g201200

**Comment by adf-ncgr** [comment]
https://legumeinfo.org/gene_links/vigun.Vigun05g296900/json

don't ask me, I didn't design the API (it was natural selection all the way)

**Comment by sammyjava** [comment]
OH, hrm, I just spaced out on the /json. Forget my email about it, I'll punch it in now.
